version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: "rusty-shorts-db"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rusty_shorts_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
