[default.databases]
rusty_shorts_db = { url = "postgres://admin:password@localhost:5432/rusty_shorts" }

[release.databases]
rusty_shorts_db = { url = "postgres://admin:password@localhost:5432/rusty_shorts" }
